import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'ar' | 'en'
type Direction = 'rtl' | 'ltr'

interface LanguageContextType {
  language: Language
  direction: Direction
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ar: {
    // Header
    'header.title': 'مصنع صباح الخير',
    'header.search': 'البحث...',
    'header.settings': 'الإعدادات',
    'header.logout': 'تسجيل الخروج',
    
    // Sidebar
    'sidebar.dashboard': 'لوحة المعلومات',
    'sidebar.users': 'إدارة المستخدمين',
    'sidebar.products': 'إدارة المنتجات',
    'sidebar.inventory': 'إدارة المخزون',
    'sidebar.purchases': 'إدارة المشتريات',
    'sidebar.production': 'إدارة الإنتاج',
    'sidebar.sales': 'إدارة المبيعات',
    'sidebar.finance': 'الإدارة المالية',
    'sidebar.hr': 'الموارد البشرية',
    'sidebar.reports': 'مركز التقارير',
    'sidebar.settings': 'إعدادات النظام',
    'sidebar.systemName': 'صباح الخير',
    'sidebar.systemDesc': 'نظام إدارة المصنع',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بك في نظام إدارة مصنع صباح الخير',
    'dashboard.description': 'نظرة شاملة على أداء المصنع والعمليات اليومية',
    'dashboard.totalSales': 'إجمالي المبيعات',
    'dashboard.totalOrders': 'عدد الطلبات',
    'dashboard.activeProducts': 'المنتجات النشطة',
    'dashboard.activeCustomers': 'العملاء النشطون',
    'dashboard.lastMonth': 'من الشهر الماضي',
    'dashboard.salesChart': 'مبيعات آخر 6 أشهر',
    'dashboard.inventoryStatus': 'حالة المخزون',
    'dashboard.recentActivities': 'الأنشطة الأخيرة',
    'dashboard.importantAlerts': 'تنبيهات مهمة',
    
    // Common
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.search': 'البحث',
    'common.filter': 'فلترة',
    'common.export': 'تصدير',
    'common.print': 'طباعة',
    'common.view': 'عرض',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.date': 'التاريخ',
    'common.total': 'الإجمالي',
    'common.quantity': 'الكمية',
    'common.price': 'السعر',
    'common.name': 'الاسم',
    'common.description': 'الوصف',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    
    // Products
    'products.title': 'إدارة المنتجات',
    'products.description': 'إدارة منتجات المصنع وتصنيفاتها',
    'products.addNew': 'إضافة منتج جديد',
    'products.totalProducts': 'إجمالي المنتجات',
    'products.activeProducts': 'المنتجات النشطة',
    'products.categories': 'الفئات',
    'products.totalStock': 'إجمالي المخزون',
    'products.searchPlaceholder': 'البحث عن المنتجات...',
    'products.allCategories': 'جميع الفئات',
    'products.allStatuses': 'جميع الحالات',
    'products.productName': 'اسم المنتج',
    'products.category': 'الفئة',
    'products.sku': 'رمز المنتج',
    'products.stock': 'المخزون',
    'products.costPrice': 'سعر التكلفة',
    'products.sellingPrice': 'سعر البيع',
    'products.profit': 'الربح',
    
    // Inventory
    'inventory.title': 'إدارة المخزون',
    'inventory.description': 'تتبع ومراقبة مستويات المخزون والحركات',
    'inventory.stockCount': 'جرد مخزون',
    'inventory.stockMovement': 'حركة مخزنية',
    'inventory.totalItems': 'إجمالي الأصناف',
    'inventory.totalQuantity': 'إجمالي الكمية',
    'inventory.belowMinimum': 'تحت الحد الأدنى',
    'inventory.stockValue': 'قيمة المخزون',
    'inventory.overview': 'نظرة عامة',
    'inventory.movements': 'حركات المخزون',
    'inventory.locations': 'مواقع التخزين',
    'inventory.searchPlaceholder': 'البحث في المخزون...',
    'inventory.currentStock': 'الكمية الحالية',
    'inventory.minimumLevel': 'الحد الأدنى',
    'inventory.maximumLevel': 'الحد الأقصى',
    'inventory.location': 'الموقع',
    'inventory.normal': 'طبيعي',
    'inventory.low': 'تحت الحد الأدنى',
    'inventory.high': 'فوق الحد الأقصى',
    
    // Production
    'production.title': 'إدارة الإنتاج',
    'production.description': 'متابعة أوامر الإنتاج والعمليات التصنيعية',
    'production.newOrder': 'أمر إنتاج جديد',
    'production.orders': 'أوامر الإنتاج',
    'production.completed': 'مكتملة',
    'production.inProgress': 'قيد التنفيذ',
    'production.totalQuantity': 'إجمالي الكمية',
    'production.materials': 'المواد الخام',
    'production.stages': 'مراحل الإنتاج',
    'production.searchPlaceholder': 'البحث في أوامر الإنتاج...',
    'production.orderNumber': 'رقم الأمر',
    'production.product': 'المنتج',
    'production.startDate': 'تاريخ البدء',
    'production.dueDate': 'تاريخ الاستحقاق',
    'production.progress': 'التقدم',
    'production.planned': 'مخطط',
    'production.delayed': 'متأخر',
    'production.requiredMaterials': 'المواد المطلوبة',
    
    // Sales
    'sales.title': 'إدارة المبيعات',
    'sales.description': 'إدارة أوامر البيع والعملاء',
    'sales.addCustomer': 'إضافة عميل',
    'sales.newOrder': 'أمر بيع جديد',
    'sales.totalSales': 'إجمالي المبيعات',
    'sales.activeCustomers': 'العملاء النشطين',
    'sales.averageOrder': 'متوسط قيمة الطلب',
    'sales.orders': 'أوامر البيع',
    'sales.customers': 'العملاء',
    'sales.quotes': 'عروض الأسعار',
    'sales.searchOrders': 'البحث في أوامر البيع...',
    'sales.searchCustomers': 'البحث في العملاء...',
    'sales.orderNumber': 'رقم الأمر',
    'sales.customer': 'العميل',
    'sales.items': 'الأصناف',
    'sales.deliveryDate': 'تاريخ التسليم',
    'sales.confirmed': 'مؤكد',
    'sales.shipped': 'تم الشحن',
    'sales.delivered': 'تم التسليم',
    'sales.pending': 'في الانتظار',
    'sales.cancelled': 'ملغي',
    'sales.totalOrders': 'إجمالي الطلبات',
    'sales.totalAmount': 'إجمالي المبلغ',
    
    // Finance
    'finance.title': 'الإدارة المالية',
    'finance.description': 'إدارة الحسابات المالية والمعاملات',
    'finance.receiptVoucher': 'سند قبض',
    'finance.paymentVoucher': 'سند صرف',
    'finance.journalEntry': 'قيد يومية',
    'finance.totalAssets': 'إجمالي الأصول',
    'finance.monthlyRevenue': 'الإيرادات الشهرية',
    'finance.monthlyExpenses': 'المصروفات الشهرية',
    'finance.netProfit': 'صافي الربح',
    'finance.overview': 'نظرة عامة',
    'finance.accounts': 'الحسابات',
    'finance.transactions': 'المعاملات',
    'finance.reports': 'التقارير المالية',
    'finance.searchAccounts': 'البحث في الحسابات...',
    'finance.searchTransactions': 'البحث في المعاملات...',
    'finance.accountName': 'اسم الحساب',
    'finance.accountType': 'النوع',
    'finance.balance': 'الرصيد',
    'finance.currency': 'العملة',
    'finance.cash': 'نقدي',
    'finance.bank': 'بنكي',
    'finance.receivable': 'مدين',
    'finance.payable': 'دائن',
    'finance.financialSummary': 'الملخص المالي',
    'finance.totalRevenue': 'إجمالي الإيرادات',
    'finance.totalExpenses': 'إجمالي المصروفات',
    'finance.cashFlow': 'التدفق النقدي',
    'finance.cashInHand': 'النقد في الصندوق',
    'finance.bankBalances': 'أرصدة البنوك',
    'finance.totalLiquidity': 'إجمالي السيولة',
    
    // HR
    'hr.title': 'إدارة الموارد البشرية',
    'hr.description': 'إدارة الموظفين والرواتب',
    'hr.processPayroll': 'معالجة رواتب',
    'hr.addEmployee': 'إضافة موظف',
    'hr.totalEmployees': 'إجمالي الموظفين',
    'hr.activeEmployees': 'الموظفين النشطين',
    'hr.totalSalaries': 'إجمالي الرواتب',
    'hr.averageService': 'متوسط سنوات الخدمة',
    'hr.employees': 'الموظفين',
    'hr.salaries': 'الرواتب',
    'hr.attendance': 'الحضور والانصراف',
    'hr.searchEmployees': 'البحث في الموظفين...',
    'hr.searchSalaries': 'البحث في الرواتب...',
    'hr.employee': 'الموظف',
    'hr.position': 'المنصب',
    'hr.department': 'القسم',
    'hr.hireDate': 'تاريخ التعيين',
    'hr.salary': 'الراتب',
    'hr.month': 'الشهر',
    'hr.basicSalary': 'الراتب الأساسي',
    'hr.allowances': 'البدلات',
    'hr.deductions': 'الخصومات',
    'hr.netSalary': 'صافي الراتب',
    'hr.paid': 'مدفوع',
    'hr.years': 'سنة',
    
    // Purchases
    'purchases.title': 'إدارة المشتريات',
    'purchases.description': 'إدارة أوامر الشراء والموردين',
    'purchases.addSupplier': 'إضافة مورد',
    'purchases.newPurchaseOrder': 'أمر شراء جديد',
    'purchases.orders': 'أوامر الشراء',
    'purchases.suppliers': 'الموردين',
    'purchases.receipts': 'إيصالات الاستلام',
    'purchases.searchOrders': 'البحث في أوامر الشراء...',
    'purchases.searchSuppliers': 'البحث في الموردين...',
    'purchases.orderNumber': 'رقم الأمر',
    'purchases.supplier': 'المورد',
    'purchases.approved': 'معتمد',
    'purchases.received': 'مستلم',
    'purchases.totalValue': 'القيمة الإجمالية',
    'purchases.activeSuppliers': 'الموردين النشطين',
    'purchases.contact': 'جهة الاتصال',
    'purchases.phone': 'الهاتف',
    'purchases.email': 'البريد الإلكتروني',
    'purchases.address': 'العنوان',
    'purchases.rating': 'التقييم',
    'purchases.ordersCount': 'عدد الطلبات',
    
    // Reports
    'reports.title': 'مركز التقارير',
    'reports.description': 'تقارير شاملة ومفصلة لجميع أقسام المصنع',
    'reports.exportReport': 'تصدير التقرير',
    'reports.today': 'اليوم',
    'reports.thisWeek': 'هذا الأسبوع',
    'reports.thisMonth': 'هذا الشهر',
    'reports.thisQuarter': 'هذا الربع',
    'reports.thisYear': 'هذا العام',
    'reports.customPeriod': 'فترة مخصصة',
    'reports.salesReports': 'تقارير المبيعات',
    'reports.inventoryReports': 'تقارير المخزون',
    'reports.purchaseReports': 'تقارير المشتريات',
    'reports.financialReports': 'التقارير المالية',
    'reports.hrReports': 'تقارير الموارد البشرية',
    'reports.generateReport': 'إنشاء التقرير',
    'reports.recentReports': 'التقارير الأخيرة',
    'reports.fromPrevious': 'من الفترة السابقة',
    
    // Settings
    'settings.title': 'إعدادات النظام',
    'settings.description': 'إدارة إعدادات النظام والشركة',
    'settings.saveSettings': 'حفظ الإعدادات',
    'settings.general': 'الإعدادات العامة',
    'settings.company': 'بيانات الشركة',
    'settings.security': 'الأمان',
    'settings.backup': 'النسخ الاحتياطي',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة',
    'settings.arabic': 'العربية',
    'settings.english': 'English',
    
    // Months
    'months.january': 'يناير',
    'months.february': 'فبراير',
    'months.march': 'مارس',
    'months.april': 'أبريل',
    'months.may': 'مايو',
    'months.june': 'يونيو',
  },
  en: {
    // Header
    'header.title': 'Sabah Al-Khair Factory',
    'header.search': 'Search...',
    'header.settings': 'Settings',
    'header.logout': 'Logout',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.users': 'User Management',
    'sidebar.products': 'Product Management',
    'sidebar.inventory': 'Inventory Management',
    'sidebar.purchases': 'Purchase Management',
    'sidebar.production': 'Production Management',
    'sidebar.sales': 'Sales Management',
    'sidebar.finance': 'Financial Management',
    'sidebar.hr': 'Human Resources',
    'sidebar.reports': 'Reports Center',
    'sidebar.settings': 'System Settings',
    'sidebar.systemName': 'Sabah Al-Khair',
    'sidebar.systemDesc': 'Factory Management System',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Sabah Al-Khair Factory Management System',
    'dashboard.description': 'Comprehensive overview of factory performance and daily operations',
    'dashboard.totalSales': 'Total Sales',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.activeProducts': 'Active Products',
    'dashboard.activeCustomers': 'Active Customers',
    'dashboard.lastMonth': 'from last month',
    'dashboard.salesChart': 'Sales Last 6 Months',
    'dashboard.inventoryStatus': 'Inventory Status',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.importantAlerts': 'Important Alerts',
    
    // Common
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    'common.view': 'View',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.total': 'Total',
    'common.quantity': 'Quantity',
    'common.price': 'Price',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    
    // Products
    'products.title': 'Product Management',
    'products.description': 'Manage factory products and categories',
    'products.addNew': 'Add New Product',
    'products.totalProducts': 'Total Products',
    'products.activeProducts': 'Active Products',
    'products.categories': 'Categories',
    'products.totalStock': 'Total Stock',
    'products.searchPlaceholder': 'Search products...',
    'products.allCategories': 'All Categories',
    'products.allStatuses': 'All Statuses',
    'products.productName': 'Product Name',
    'products.category': 'Category',
    'products.sku': 'SKU',
    'products.stock': 'Stock',
    'products.costPrice': 'Cost Price',
    'products.sellingPrice': 'Selling Price',
    'products.profit': 'Profit',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.description': 'Track and monitor inventory levels and movements',
    'inventory.stockCount': 'Stock Count',
    'inventory.stockMovement': 'Stock Movement',
    'inventory.totalItems': 'Total Items',
    'inventory.totalQuantity': 'Total Quantity',
    'inventory.belowMinimum': 'Below Minimum',
    'inventory.stockValue': 'Stock Value',
    'inventory.overview': 'Overview',
    'inventory.movements': 'Stock Movements',
    'inventory.locations': 'Storage Locations',
    'inventory.searchPlaceholder': 'Search inventory...',
    'inventory.currentStock': 'Current Stock',
    'inventory.minimumLevel': 'Minimum Level',
    'inventory.maximumLevel': 'Maximum Level',
    'inventory.location': 'Location',
    'inventory.normal': 'Normal',
    'inventory.low': 'Below Minimum',
    'inventory.high': 'Above Maximum',
    
    // Production
    'production.title': 'Production Management',
    'production.description': 'Track production orders and manufacturing operations',
    'production.newOrder': 'New Production Order',
    'production.orders': 'Production Orders',
    'production.completed': 'Completed',
    'production.inProgress': 'In Progress',
    'production.totalQuantity': 'Total Quantity',
    'production.materials': 'Raw Materials',
    'production.stages': 'Production Stages',
    'production.searchPlaceholder': 'Search production orders...',
    'production.orderNumber': 'Order Number',
    'production.product': 'Product',
    'production.startDate': 'Start Date',
    'production.dueDate': 'Due Date',
    'production.progress': 'Progress',
    'production.planned': 'Planned',
    'production.delayed': 'Delayed',
    'production.requiredMaterials': 'Required Materials',
    
    // Sales
    'sales.title': 'Sales Management',
    'sales.description': 'Manage sales orders and customers',
    'sales.addCustomer': 'Add Customer',
    'sales.newOrder': 'New Sales Order',
    'sales.totalSales': 'Total Sales',
    'sales.activeCustomers': 'Active Customers',
    'sales.averageOrder': 'Average Order Value',
    'sales.orders': 'Sales Orders',
    'sales.customers': 'Customers',
    'sales.quotes': 'Quotes',
    'sales.searchOrders': 'Search sales orders...',
    'sales.searchCustomers': 'Search customers...',
    'sales.orderNumber': 'Order Number',
    'sales.customer': 'Customer',
    'sales.items': 'Items',
    'sales.deliveryDate': 'Delivery Date',
    'sales.confirmed': 'Confirmed',
    'sales.shipped': 'Shipped',
    'sales.delivered': 'Delivered',
    'sales.pending': 'Pending',
    'sales.cancelled': 'Cancelled',
    'sales.totalOrders': 'Total Orders',
    'sales.totalAmount': 'Total Amount',
    
    // Finance
    'finance.title': 'Financial Management',
    'finance.description': 'Manage financial accounts and transactions',
    'finance.receiptVoucher': 'Receipt Voucher',
    'finance.paymentVoucher': 'Payment Voucher',
    'finance.journalEntry': 'Journal Entry',
    'finance.totalAssets': 'Total Assets',
    'finance.monthlyRevenue': 'Monthly Revenue',
    'finance.monthlyExpenses': 'Monthly Expenses',
    'finance.netProfit': 'Net Profit',
    'finance.overview': 'Overview',
    'finance.accounts': 'Accounts',
    'finance.transactions': 'Transactions',
    'finance.reports': 'Financial Reports',
    'finance.searchAccounts': 'Search accounts...',
    'finance.searchTransactions': 'Search transactions...',
    'finance.accountName': 'Account Name',
    'finance.accountType': 'Type',
    'finance.balance': 'Balance',
    'finance.currency': 'Currency',
    'finance.cash': 'Cash',
    'finance.bank': 'Bank',
    'finance.receivable': 'Receivable',
    'finance.payable': 'Payable',
    'finance.financialSummary': 'Financial Summary',
    'finance.totalRevenue': 'Total Revenue',
    'finance.totalExpenses': 'Total Expenses',
    'finance.cashFlow': 'Cash Flow',
    'finance.cashInHand': 'Cash in Hand',
    'finance.bankBalances': 'Bank Balances',
    'finance.totalLiquidity': 'Total Liquidity',
    
    // HR
    'hr.title': 'Human Resources Management',
    'hr.description': 'Manage employees and payroll',
    'hr.processPayroll': 'Process Payroll',
    'hr.addEmployee': 'Add Employee',
    'hr.totalEmployees': 'Total Employees',
    'hr.activeEmployees': 'Active Employees',
    'hr.totalSalaries': 'Total Salaries',
    'hr.averageService': 'Average Years of Service',
    'hr.employees': 'Employees',
    'hr.salaries': 'Salaries',
    'hr.attendance': 'Attendance',
    'hr.searchEmployees': 'Search employees...',
    'hr.searchSalaries': 'Search salaries...',
    'hr.employee': 'Employee',
    'hr.position': 'Position',
    'hr.department': 'Department',
    'hr.hireDate': 'Hire Date',
    'hr.salary': 'Salary',
    'hr.month': 'Month',
    'hr.basicSalary': 'Basic Salary',
    'hr.allowances': 'Allowances',
    'hr.deductions': 'Deductions',
    'hr.netSalary': 'Net Salary',
    'hr.paid': 'Paid',
    'hr.years': 'years',
    
    // Purchases
    'purchases.title': 'Purchase Management',
    'purchases.description': 'Manage purchase orders and suppliers',
    'purchases.addSupplier': 'Add Supplier',
    'purchases.newPurchaseOrder': 'New Purchase Order',
    'purchases.orders': 'Purchase Orders',
    'purchases.suppliers': 'Suppliers',
    'purchases.receipts': 'Receipts',
    'purchases.searchOrders': 'Search purchase orders...',
    'purchases.searchSuppliers': 'Search suppliers...',
    'purchases.orderNumber': 'Order Number',
    'purchases.supplier': 'Supplier',
    'purchases.approved': 'Approved',
    'purchases.received': 'Received',
    'purchases.totalValue': 'Total Value',
    'purchases.activeSuppliers': 'Active Suppliers',
    'purchases.contact': 'Contact',
    'purchases.phone': 'Phone',
    'purchases.email': 'Email',
    'purchases.address': 'Address',
    'purchases.rating': 'Rating',
    'purchases.ordersCount': 'Orders Count',
    
    // Reports
    'reports.title': 'Reports Center',
    'reports.description': 'Comprehensive and detailed reports for all factory departments',
    'reports.exportReport': 'Export Report',
    'reports.today': 'Today',
    'reports.thisWeek': 'This Week',
    'reports.thisMonth': 'This Month',
    'reports.thisQuarter': 'This Quarter',
    'reports.thisYear': 'This Year',
    'reports.customPeriod': 'Custom Period',
    'reports.salesReports': 'Sales Reports',
    'reports.inventoryReports': 'Inventory Reports',
    'reports.purchaseReports': 'Purchase Reports',
    'reports.financialReports': 'Financial Reports',
    'reports.hrReports': 'HR Reports',
    'reports.generateReport': 'Generate Report',
    'reports.recentReports': 'Recent Reports',
    'reports.fromPrevious': 'from previous period',
    
    // Settings
    'settings.title': 'System Settings',
    'settings.description': 'Manage system and company settings',
    'settings.saveSettings': 'Save Settings',
    'settings.general': 'General Settings',
    'settings.company': 'Company Information',
    'settings.security': 'Security',
    'settings.backup': 'Backup',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.arabic': 'العربية',
    'settings.english': 'English',
    
    // Months
    'months.january': 'January',
    'months.february': 'February',
    'months.march': 'March',
    'months.april': 'April',
    'months.may': 'May',
    'months.june': 'June',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ar')
  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr'

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const value = {
    language,
    direction,
    setLanguage,
    t
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}